# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chatgpt-search"
version = "0.1.1"
description = "test package for search with chatgpt in cli"
readme = "README.md"
authors = [{ name = "Abhijeet Kumar", email = "krabhijeet93@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["search"]
dependencies = [
    "openai",
    "html2text",
    "sgmllib3k",
    "tomli",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/abhijeetkr93/chatgpt-search"

[project.scripts]
search = "src.search.__main__:main"