#[chatgpt]
#model = "code-davinci-003"
#temperature = 0
#max_tokens = 1000
#top_p = 0
#log_probs = 10
#frequency_penalty = 0
#presence_penalty = 0

[chatgpt]
model = "code-davinci-002"
max_tokens=256
top_p=1
frequency_penalty=0
presence_penalty=0
