[text-long-qa]
model="text-davinci-003"
prompt=""
temperature=0
max_tokens=100
top_p=1
frequency_penalty=0
presence_penalty=0
stop="\n"

[text-completion]
model="text-davinci-003"
prompt="Brainstorm some ideas combining:"
temperature=0.6
max_tokens=1500
top_p=1
frequency_penalty=1
presence_penalty=1

[text-qa]
model="text-davinci-003"
prompt=""
temperature=0
max_tokens=60
top_p=1.0
frequency_penalty=0.0
presence_penalty=0.0

[text-ml]
model="text-davinci-003"
prompt=""
temperature=0.3
max_tokens=60
top_p=1.0
frequency_penalty=0.5
presence_penalty=0.0
stop="You:"

[code]
model="code-davinci-002"
prompt=""
temperature=0
max_tokens=60
top_p=1.0
frequency_penalty=0.5
presence_penalty=0.0
stop="You:"
